name: wisconsin_app
description: Wisconsin Rut Report Project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

  #Screen Utilization 
  flutter_screenutil: ^5.5.3+2

  #State Management
  provider: ^6.0.3

  #Svg file view
  flutter_svg: ^1.0.3

  #HTTP request package
  dio: ^4.0.6

  #Loading spinner
  loading_indicator: ^3.0.3

  #picking image from store
  image_picker: ^0.8.5+3

  #page pull to refresh
  pull_to_refresh: ^2.0.0

  #Localization/Date formating
  intl: ^0.17.0

  #Network Image Caching
  cached_network_image: ^3.2.0

  #Local store data caching
  shared_preferences: ^2.0.15

  #Popup Menu Items
  focused_menu: ^1.0.5

  #Image preview package
  photo_view: ^0.14.0
  
  #Chart package
  # fl_chart: ^0.55.0

  #URL launcher
  url_launcher: ^6.1.5

  #Web content to flutter widget
  flutter_widget_from_html: ^0.8.5
  webview_flutter_plus: ^0.3.0+2

  #RevenueCat subscription package
  purchases_flutter: ^3.10.0

  #video content handling
  video_player: ^2.4.6
  chewie: ^1.3.5

  #Video utility
  video_compress: ^3.1.1
  
  #Screen orientation handling
  auto_orientation: ^2.2.1

  #Push notification
  firebase_core: ^1.22.0
  firebase_messaging: ^13.0.0

  #Local Notification
  flutter_local_notifications: ^9.9.1
  rxdart: ^0.27.5

  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  
  # App launcher icon 
  flutter_launcher_icons: ^0.9.2
  #Get native splash screen
  flutter_native_splash: ^2.1.6
  freezed: ^0.14.1+1
  build_runner:

# App launcher icon configurations
flutter_icons:
  android: false
  ios: true
  image_path: "assets/icons/wrr.png"
  adaptive_icon_background: "assets/icons/wrr_adaptive_back.png"
  adaptive_icon_foreground: "assets/icons/wrr_adaptive_fore.png"

# Splash Screen configurations
flutter_native_splash:
  color: "#0E131D"
  image: "assets/images/logo-1080.png"
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/html/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 200              
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400          
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages