import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_widget_from_html/flutter_widget_from_html.dart';

class RulesPage extends StatelessWidget {
  const RulesPage({Key? key}) : super(key: key);

  final String kHtml = """
<p style="text-align: center;"><span style="color: #999999;"><strong>Wisconsin Rut Report Buck Contest Rules</strong></span></p>
<p style="text-align: justify;"><span style="color: #999999;">This Participation Agreement shall be used solely for the tournaments and events produced, sponsored, or coordinated by Wisconsin Rut Report LLC (&ldquo;Wisconsin Rut Report&rdquo;).&nbsp; Wisconsin Rut Report shall have exclusive authority to interpret and enforce the terms of the Participation Agreement.&nbsp; Wisconsin Rut Report reserves the right to amend and/or modify this Participation Agreement.&nbsp; It is the sole responsibility of each registered hunter to read and understand the Participation Agreement and the Complete Waiver and Release of Liability Agreement to Hold Harmless and Assumption of Risk (&ldquo;Waiver&rdquo;).&nbsp; The Participation Agreement and the Waiver, as well as any and all updates and changes thereto, shall be available at www.wisconsinrutreport.com.&nbsp; For purposes of this Participation Agreement, &ldquo;deer&rdquo; means White-tailed Deer.&nbsp; No other species of deer will be accepted. For purposes of this Participation Agreement, each deer must be harvested in the State of Wisconsin, with a legal hunting license and tag. Wisconsin DNR Harvest number and confirmation must be supplied to Wisconsin Rut Report to allow entry.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">AGE REQUIREMENT.&nbsp; Participants must be at least 13 years of age as of the start of the deer season in their state to enter. Any participant who is under the age of 18 at the start of the deer season in Wisconsin must have parental consent form filled out and signed by a guardian.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">NO PROFESSIONAL HUNTER.&nbsp; Any person who is a Professional Hunter is ineligible for the Wisconsin Rut Report Buck Contest.&nbsp; For the purposes of this Agreement, a Professional Hunter is defined as a person who receives any income from hunting deer and/or a person who receives any income from creating footage, whether in video, audio, or other electronic forms, of deer hunting.&nbsp; In the event Wisconsin Rut Report becomes aware that a Professional Hunter has registered with Wisconsin Rut Reports Buck Contest, the Professional Hunter shall be immediately and permanently disqualified from Wisconsin Rut Report competitions and events.&nbsp; The Professional Hunter understands and agrees that his/her registration fee and any and all prizes or money obtained through Wisconsin Rut Report shall be forfeited.</span></p>
<p><span style="color: #999999;">CONTEST DATES</span></p>
<p><span style="color: #999999;">Wisconsin Archery Season: 9/17/2022 &ndash; 1/8/2023</span></p>
<p><span style="color: #999999;">Wisconsin Gun Season: 11/19/2022 &ndash; 11/27/2022</span></p>
<p><span style="color: #999999;">Wisconsin Muzzleloader Season: 11/28/2022 &ndash; 12/7/2022</span></p>
<p style="text-align: justify;"><span style="color: #999999;">ENTRY DEADLINE.&nbsp; All Contestants registration and Waiver must be fully complete prior to any submission of a harvested deer.&nbsp; No deer harvested prior to full completion of registration and Waiver shall be considered in determining any prize.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">STATE REQUIREMENT.&nbsp; Each hunter must hunt in Wisconsin.&nbsp; In the event a hunter harvests a deer in a different state, or on land that the hunter does not have permission on which to hunt, that hunter shall be immediately disqualified from the Wisconsin Rut Report Buck Contest, and Wisconsin Rut Report may take further actions as it sees fit to sanction the violation.&nbsp;</span></p>
<p style="text-align: justify;"><span style="color: #999999;">PROHIBITED ACTIVITIES.&nbsp; The hunter shall not use any and all &ldquo;high-fence&rdquo; methods and/or participate in game-farm hunting for the competition.&nbsp; In the event Wisconsin Rut Report becomes aware that any hunter registered with Wisconsin Rut Report Buck Contest enters or submits a buck harvested from a high-fence or game farm hunt, the hunter taking that buck shall be immediately and permanently disqualified from Wisconsin Rut Report competitions and events.&nbsp; That hunter further understands and agrees that his/her registration fee and any and all prizes or money obtained through the Wisconsin Rut Report shall be forfeited.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">FAMILY MEMBERS.&nbsp; Immediate family members of owners, officers, and employees of Wisconsin Rut Report are strictly prohibited from participating in this hunting competition.&nbsp; In the event Wisconsin Rut Report becomes aware that a family member of an owner, officer, or employee of Wisconsin Rut Report has registered with Wisconsin Rut Report Buck Contest, the family member shall be immediately and permanently disqualified from Wisconsin Rut Report competitions and events.&nbsp; The family member understands and agrees that his/her registration fee and any and all prizes or money obtained through Wisconsin Rut Report shall be forfeited.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">SCORE AND PRIZES.&nbsp; Deer must be scored and submitted within 36 hours of harvest with antlers fully intact and prior to caping of the deer except as outlined below. Score is inside spread of antlers, length of both main beams, number of tines, length of all tines (video linked for instruction). &nbsp;For the purposes of this Agreement, &ldquo;Harvest&rdquo; shall be defined as the actual time of physical recovery of the deer shot by participant.&nbsp; If a deer is unable to be physically recovered by 11:59 p.m. on the day it was shot, participants are required to notify Wisconsin Rut Report (ethan@wisconsinrutreport.com) by 12:00 p.m. (noon) the following day.&nbsp; Once the participant has notified Wisconsin Rut Report, the participant has 36 hours to recover, score and submit the deer for it to be accepted.&nbsp; Any deer submitted after the 36 hours have elapsed will not be accepted or considered for official scoring. An individual shall only submit one deer for official scoring.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">All prizes received from placement in the Wisconsin Rut Report Buck Contest or from giveaways by Wisconsin Rut Report are final. No prizes may be returned or exchanged.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">The Official Score:&nbsp; Official scoring may begin up to a day in advance of any banquet. After submitting an unofficial score as provided above, individuals placing 1st-6th are required to attend the official scoring and awards ceremony.&nbsp; All individuals in place 1-6 are required to attend the final banquet to receive prizes. Individuals are required to have your deer&rsquo;s rack submitted for scoring at the official scoring and awards ceremony.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">After submission of the deer as provided in this paragraph, certified scorers selected by Wisconsin Rut Report shall measure the deer and provide an official score.&nbsp; Any Participant who wishes to have their deer scored in consideration of winning prizes must be present for official scoring.&nbsp; Any deer that has previously been officially dry scored prior to the Wisconsin Rut Report banquet will not be accepted and will not be considered for official scoring and prizes.&nbsp; Deer must be scored by the selected scorers of Wisconsin Rut Report at the designated time of official scoring at the banquet to be considered for official scoring and prizes.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">Additionally, to be considered for official scoring, deer must be presented fully intact.&nbsp; Any shed, broken antler or skull plate not fully intact will be not considered for official scoring.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">All Official Scores are final and are not subject to revision. Scores provided by the selected scoring team of Wisconsin Rut Report are the Official Scores and are not subject to change.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">BANQUET AND OFFICIAL SCORING LOCATION</span></p>
<p style="text-align: justify;"><span style="color: #999999;">TBD</span></p>
<p style="text-align: justify;"><span style="color: #999999;">Any hunter will be required to show proof of tagging the deer submitted.&nbsp; Any hunter who fails to strictly comply with the requirements outlined in this section shall be immediately disqualified, shall forfeit the registration fee, and be ineligible for any and all prizes.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">PRIZE QUALIFICATION.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">TBD</span></p>
<p style="text-align: justify;"><span style="color: #999999;"><strong>COMPLIANCE WITH FEDERAL AND STATE HUNTING LAWS, REGULATIONS, AND ORDINANCES.</strong>&nbsp; Each and every hunter registered with Wisconsin Rut Report shall strictly adhere to any and all applicable Federal and State hunting laws, regulations, and ordinances.&nbsp; A violation of any Federal or State hunting law, regulation, or ordinance shall result in immediate disqualification of the violating hunter from Wisconsin Rut Report Buck Contest.&nbsp; Moreover, any information obtained by Wisconsin Rut Report from the violating hunter shall be provided to the appropriate law enforcement agency.&nbsp; Wisconsin Rut Report will cooperate with all law enforcement with respect to any violation or suspected violation of hunting laws, regulations, or ordinances.&nbsp; In the event Wisconsin Rut Report becomes aware that a hunter may have violated a hunting law, regulation, or ordinance, or that a hunter may have violated one of these Rules &amp; Regulations, Wisconsin Rut Report has sole discretion to investigate such violation and take whatever action it sees fit in response thereto.&nbsp; All hunters registered with Wisconsin Rut Report Buck Contest agree and understand that Wisconsin Rut Report and the Wisconsin Rut Report Rules and Regulations Enforcement Committee have the exclusive authority to take this action, and that such action is not appealable to any forum or tribunal.</span></p>
<p style="text-align: justify;"><span style="color: #999999;"><strong>HUNTING LICENSE.</strong>&nbsp; Each hunter is responsible for obtaining and paying for his/her own license, permit, and/or game tag to hunt in Wisconsin.&nbsp; In the event a hunter does not obtain a valid license, that hunter shall be immediately and permanently disqualified from Wisconsin Rut Report Buck Contest.&nbsp; All hunters acknowledge and agree that Wisconsin Rut Report is not liable or responsible for the hunter not being issued a license or game tag.</span></p>
<p style="text-align: justify;"><span style="color: #999999;"><strong>USE OF PHOTOGRAPHS/VIDEO/RECORDINGS.</strong>&nbsp; Each and every participant provides an irrevocable license to Wisconsin Rut Report for the use of any and all photographs, videos, and recordings of any kind of the Hunter taken during or while observing a Wisconsin Rut Report competition.&nbsp;</span></p>
<p style="text-align: justify;"><span style="color: #999999;">Use of any Wisconsin Rut Report trademarks, logos, photos, videos or other proprietary information is strictly prohibited without the express written consent of Wisconsin Rut Report.</span></p>
<p style="text-align: justify;"><span style="color: #999999;">SAFETY; WAIVER AND RELEASE OF LIABILITY.&nbsp; EACH AND EVERY HUNTER WHO REGISTERS WITH WISCONSIN RUT REPORT UNDERSTANDS AND ACKNOWLEDGES THE PARAMOUNT REQUIREMENT OF A SAFE HUNT.&nbsp; EACH AND EVERY HUNTER SHALL READ, UNDERSTAND AND EXECUTE THE COMPLETE WAIVER AND RELEASE OF LIABILITY AGREEMENT TO HOLD HARMLESS AND ASSUMPTION OF RISK, WHICH TERMS AND CONDITIONS ARE INCORPORATED HEREIN BY REFERENCE.</span></p>
""";

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: SingleChildScrollView(
        padding: EdgeInsets.symmetric(vertical: 10.h, horizontal: 10.w),
        physics: const BouncingScrollPhysics(),
        child: HtmlWidget(
          kHtml,
        ),
      ),
    );
  }
}
